# Generated by Django 5.0.2 on 2024-06-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('BR', 'Borrador'), ('PB', 'Publicado')], default='BR', max_length=2),
        ),
    ]
