# Generated by Django 5.0.2 on 2024-06-07 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
